CREATE TABLE ADDRESS (

ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
STREETNAME VARCHAR(30) NOT NULL,
NUMBER INT (10) NOT NULL,
COMPLEMENT VARCHAR(15),
NEIGHBOURHOOD VARCHAR(15) NOT NULL,
CITY VARCHAR(15) NOT NULL,
STATE VARCHAR(15) NOT NULL,
COUNTRY VARCHAR(15) NOT NULL,
ZIPCODE VARCHAR (20) NOT NULL,
LATITUDE DOUBLE (20) ,
LONGITUDE DOUBLE (20)
);


